export type SettingsHandler = (...args: unknown[]) => void;
export type SettingsSoundId = "tap" | "click" | "success" | "error" | "back" | "open" | "close";
export type SettingsConfig = {
  display?: { theme_mode?: string; controller_deadzone?: number };
  audio?: { ambient_enabled?: boolean; ambient_volume?: number; ambient_path?: string | null; ambient_is_folder?: boolean; ambient_shuffle?: boolean; ui_sounds_volume?: number };
  emulators?: { retroarch_use_beta_profile?: boolean };
};
export type SettingsEmulator = { id: string | number; name: string; install_type?: string; installed_path?: string | null; is_installed?: boolean; has_download?: boolean; version?: string | null; supported_platforms: string[]; download_size_bytes?: number | null };
export type MissingCore = { platform_id?: string; platform_name?: string; core_filename?: string; required?: boolean; status?: string };
export type CoreInventory = { platform_id?: string; platform_name?: string; core_filename?: string; required?: boolean; status?: string };
export type NativeController = { device_id: string | number; name: string; configured?: boolean };
export type SettingsPlatform = { id: string; name: string };
export type SettingsGame = { id: string | number; name: string; platform_id?: string };
export type SettingsPanelProps = {
  [key: string]: unknown;
  accentHue: number | null;
  activeRomDownloadCount: number;
  ambientEnabled: boolean;
  ambientIsFolder: boolean;
  ambientPath: string | null;
  ambientShuffle: boolean;
  ambientVolume: number;
  appVersion: string;
  availableEmus: SettingsEmulator[];
  config: SettingsConfig;
  controllerDeadzone: number;
  downloadingCore: string | null;
  emuInstallProgress: Record<string | number, { phase?: string; downloaded?: number; total?: number | null; percent?: number | null }>;
  emuMenuAnchor: HTMLElement | null;
  emuMessage: { type: "error" | "warning" | "info" | "success"; message: string } | null;
  expandedEmu: string | number | null;
  fullscreenEnabled: boolean;
  hiddenDialogOpen: boolean;
  hiddenGames: SettingsGame[];
  hiddenLoading: boolean;
  immersiveModeEnabled: boolean;
  installedEmus: SettingsEmulator[];
  missingCores: MissingCore[];
  nativeControllerCapture: string | null;
  nativeControllerLoading: boolean;
  nativeControllerMessage: { type: "error" | "warning" | "info" | "success"; message: string } | null;
  nativeControllers: NativeController[];
  pendingChannel: string;
  pendingRomsDirectory: string;
  platforms: [SettingsPlatform, number][];
  platformDefaults: Record<string, string | number>;
  retroarchCoreInventory: CoreInventory[];
  rommAuthMode: "pairing" | "token";
  rommDeviceName: string;
  rommDirectToken: string;
  rommDisconnectDialogOpen: boolean;
  rommPairing: { device_code: string; user_code: string } | null;
  rommSessionActive: boolean;
  rommStatus: { type: "error" | "warning" | "info" | "success"; message: string } | null;
  rommSyncMetadata: { autoSync: boolean; lastSyncedAt: string | null; libraryCount: number | null };
  rommUrl: string;
  rommUrlLocked: boolean;
  romsDirectory: string;
  scanMessage: { type: "error" | "warning" | "info" | "success"; message: string } | null;
  selectedEmu: SettingsEmulator | null;
  signedUpdateInstalling: boolean;
  storageChangeBusy: boolean;
  storageLoading: boolean;
  storageMigrationDialogOpen: boolean;
  storageOverview: { migratable_rom_count?: number; migratable_rom_bytes?: number; tracked_rom_count?: number; tracked_rom_bytes?: number; free_disk_bytes?: number; roms_directory?: string; locations?: Array<{ key: string; label: string; path: string; exists: boolean; bytes?: number }> } | null;
  supportMessage: { type: "error" | "warning" | "info" | "success"; message: string } | null;
  themeMode: "light" | "dark" | "system";
  uiSoundsEnabled: boolean;
  uiSoundsVolume: number;
  updateChannel: string;
  updateCheckLoading: boolean;
  updateCheckResult: { error?: string; channel?: string; is_update_available: boolean; signed_update_manifest_url?: string | null; release_url?: string | null; latest_version?: string | null } | null;
  updateMessage: { type: "error" | "warning" | "info" | "success"; message: string } | null;
  updatePreference: string;
  unavailableEmus: SettingsEmulator[];
  applyRomsDirectoryChange: SettingsHandler;
  cancelDevicePairing: SettingsHandler;
  cancelPrereleaseLeave: SettingsHandler;
  clearAmbientSource: SettingsHandler;
  confirmPrereleaseLeave: SettingsHandler;
  defaultGamepadDeadzone: number;
  gamepadDeadzoneMin: number;
  gamepadDeadzoneMax: number;
  getInstallTypeLabel: SettingsHandler;
  handleApplyPaths: SettingsHandler;
  handleCaptureNativeController: SettingsHandler;
  handleChangeRomsDirectory: SettingsHandler;
  handleCheckForUpdates: SettingsHandler;
  handleConnectRomM: SettingsHandler;
  handleCopyEmulatorPath: SettingsHandler;
  handleDownloadCore: SettingsHandler;
  handleDownloadEmulator: SettingsHandler;
  handleEmuMenuClose: SettingsHandler;
  handleEmuMenuOpen: SettingsHandler;
  handleDisconnectRomM: SettingsHandler;
  handleInstallSignedUpdateFromSettings: SettingsHandler;
  handleLaunchEmulator: SettingsHandler;
  handleOpenHiddenDialog: SettingsHandler;
  handleOpenLocation: SettingsHandler;
  handleOpenLogsFolder: SettingsHandler;
  handleOpenRetroarchInputSetup: SettingsHandler;
  handleOpenStorageLocation: SettingsHandler;
  handleReportProblem: SettingsHandler;
  handleRepairRetroarchProfile: SettingsHandler;
  handleResetRetroarchControllerAdditions: SettingsHandler;
  handleResetRomsDirectory: SettingsHandler;
  handleRetroarchBetaProfileChange: SettingsHandler;
  handleScanCustomDirectory: SettingsHandler;
  handleScanDirectory: SettingsHandler;
  handleSetDefaultEmulator: SettingsHandler;
  handleSyncRomM: SettingsHandler;
  handleUnhideGame: SettingsHandler;
  handleUninstallEmulator: SettingsHandler;
  loadEmulators: SettingsHandler;
  loadMissingCores: SettingsHandler;
  loadNativeControllers: SettingsHandler;
  normalizeGamepadDeadzone: SettingsHandler;
  persistAmbient: SettingsHandler;
  persistControllerDeadzone: SettingsHandler;
  persistDisplayFlags: SettingsHandler;
  persistUiSounds: SettingsHandler;
  persistUiSoundsVolume: SettingsHandler;
  persistUpdatePreference: SettingsHandler;
  pickAmbientFile: SettingsHandler;
  pickAmbientFolder: SettingsHandler;
  previewArgosySound: SettingsHandler;
  requestChannelChange: SettingsHandler;
  setAccentHue: SettingsHandler;
  setAmbientVolume: SettingsHandler;
  setControllerDeadzone: SettingsHandler;
  setEmuMessage: SettingsHandler;
  setExpandedEmu: SettingsHandler;
  setFullscreenEnabled: SettingsHandler;
  setHiddenDialogOpen: SettingsHandler;
  setImmersiveModeEnabled: SettingsHandler;
  setPendingRomsDirectory: SettingsHandler;
  setRommAuthMode: SettingsHandler;
  setRommDeviceName: SettingsHandler;
  setRommDirectToken: SettingsHandler;
  setRommDisconnectDialogOpen: SettingsHandler;
  setRommUrl: SettingsHandler;
  setStorageMigrationDialogOpen: SettingsHandler;
  setThemeMode: SettingsHandler;
  setUiSoundsVolume: SettingsHandler;
  setUpdateMessage: SettingsHandler;
  onFullscreenChange: SettingsHandler | null;
  onImmersiveModeChange: SettingsHandler | null;
  onLibraryChange: SettingsHandler | null;
  argosySoundEntries: Array<{ id: SettingsSoundId; label: string }>;
  accentHue: number | null;
};
