[romm]
auto_sync = false
sync_saves = false

[library]
scan_subdirectories = true
auto_extract_archives = true
show_hidden_games = false

[display]
theme = "Dark"
grid_columns = 5
show_platform_icons = true
show_play_time = true
cover_aspect_ratio = "Vertical"
big_picture = false
fullscreen = false
ui_sounds_enabled = false
retroachievements_enabled = false
controller_deadzone = 0.35

[emulators]
retroarch_install_kind = "external"
retroarch_use_beta_profile = false

[emulators.platform_defaults]

[audio]
ui_sounds_volume = 80
ambient_enabled = false
ambient_volume = 35
ambient_is_folder = false
ambient_shuffle = false

[updater]
check_on_startup = true
auto_update_enabled = false
channel = "stable"
