#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

EVIDENCE_DIR="${EVIDENCE_DIR:-.scratch/next-steps/evidence}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)}"
REPORT_FILE="${REPORT_FILE:-$EVIDENCE_DIR/$RUN_ID-windows-beta-certification.md}"

mkdir -p "$EVIDENCE_DIR"

record_result() {
  local area="$1" check="$2" result="$3" notes="$4" evidence="$5"
  {
    printf '\n## %s — %s\n\n' "$area" "$check"
    printf -- '- **Result:** %s\n' "$result"
    printf -- '- **Notes:** %s\n' "${notes:-None recorded}"
    printf -- '- **Evidence:** %s\n' "${evidence:-None recorded}"
  } >> "$REPORT_FILE"
}

capture_result() {
  local area="$1" check="$2" result="" notes="" evidence=""
  while [[ ! "$result" =~ ^(PASS|FAIL|SKIP)$ ]]; do
    ask result "Result for $check (PASS, FAIL, or SKIP):"
    result=$(printf '%s' "$result" | tr '[:lower:]' '[:upper:]')
    [[ "$result" =~ ^(PASS|FAIL|SKIP)$ ]] || warn "Enter PASS, FAIL, or SKIP."
  done
  ask notes "Short non-sensitive notes (no ROM names, URLs, tokens, or personal paths):"
  ask evidence "Evidence filename(s), command log, CI run, or local-only reference:"
  record_result "$area" "$check" "$result" "$notes" "$evidence"
}

certify_platform() {
  local platform="$1" core="$2"
  say "Use legally permitted homebrew/test content for $platform and the exact candidate installer."
  step "In Settings > Emulators, install/detect Wingosy-managed RetroArch and confirm the recorded manifest version."
  step "Install/resolve $core and record the RetroArch/core versions without recording the content title or path."
  step "Before the first download, briefly disable networking, select Play, and confirm a clear failure. Re-enable networking and retry successfully."
  step "On the successful first Play, confirm the permitted remote content downloads, RetroArch starts with $core, enters fullscreen, accepts controller input, exits cleanly, and returns to Wingosy."
  step "Play again and confirm the cached copy launches without another content download."
  capture_result "Plan 06" "$platform / $core real Windows runtime"
}

banner "Wingosy Windows beta certification"

stage "Clean Windows 11 preflight"
say "Run this on a clean Windows 11 machine or VM. Physical controller stages still require real XInput hardware."
warn "Use permitted homebrew/test content only. Never record credentials, signing keys, RomM URLs, ROM names/paths, database contents, or personal path segments."
step "Back up any existing %APPDATA%\\wingosy\\launcher data, emulator saves, and test content outside the profile under test."
step "Confirm Microsoft Edge, Rust stable/MSVC, Bun 1.3.14+, and Git are installed."
if ! confirm "Is the clean test environment backed up and ready?"; then
  warn "Stopping before certification."
  exit 1
fi
ask WINDOWS_VERSION "Windows 11 edition/version/build:"
ask APP_VERSION "Candidate Wingosy version:"
ask TEST_COMMIT "Exact candidate commit SHA:"
ask INSTALLER_ID "Installer filename/version (no personal path):"
ask TESTER "Tester name or non-sensitive handle:"
{
  printf '# Wingosy Windows beta certification — %s\n\n' "$RUN_ID"
  printf -- '- **Windows:** %s\n' "$WINDOWS_VERSION"
  printf -- '- **Wingosy:** %s\n' "$APP_VERSION"
  printf -- '- **Candidate commit:** %s\n' "$TEST_COMMIT"
  printf -- '- **Installer:** %s\n' "$INSTALLER_ID"
  printf -- '- **Tester:** %s\n' "$TESTER"
  printf -- '- **Safety:** No credentials, keys, user data, copyrighted content, ROM names, or personal paths belong in this report.\n'
} > "$REPORT_FILE"
say "Certification report: $REPORT_FILE"
pause "Press Enter after confirming the installer and source tree both identify the candidate commit."

stage "Automated Windows and WebDriver gates"
say "From a clean checkout of the exact candidate commit, run these commands in order and save the complete terminal output locally:"
step "bun install --frozen-lockfile"
step "bun run build"
step "bun run lint:frontend"
step "bun run typecheck"
step "bun run test:unit"
step "bun run test:rust"
step "bun run lint:rust"
step "cargo install tauri-driver"
step "bun run tauri build"
step "bun run test:e2e"
note "The E2E result must show individual specs/cases executing, not only worker startup. Do not delete, weaken, or skip a failure to publish."
capture_result "Plan 06" "Windows build, lint, typecheck, unit, Rust, Clippy, and full E2E"

stage "RetroArch NES certification"
certify_platform "NES" "fceumm_libretro.dll"

stage "RetroArch SNES certification"
certify_platform "SNES" "snes9x_libretro.dll"

stage "RetroArch Game Boy certification"
certify_platform "Game Boy" "gambatte_libretro.dll"

stage "RetroArch Game Boy Color certification"
certify_platform "Game Boy Color" "gambatte_libretro.dll"

stage "RetroArch Game Boy Advance certification"
certify_platform "Game Boy Advance" "mgba_libretro.dll"

stage "RetroArch Genesis certification"
certify_platform "Genesis / Mega Drive" "genesis_plus_gx_libretro.dll"

stage "Save round-trip and managed-profile repair"
say "Use one certified platform and a permitted title that creates an ordinary battery-backed save."
step "Back up the test save, record its non-sensitive timestamp/size or hash locally, launch through Wingosy, change the in-game save, and exit cleanly."
step "Use the supported manual save upload/download flow, then relaunch and prove the intended save state returns."
step "If the round-trip cannot be proven, record FAIL and keep automatic save sync experimental."
step "For a managed RetroArch install, open Settings > Emulators > RetroArch > Repair Wingosy RetroArch profile."
step "Confirm the generated Wingosy delta and manifest-owned artifacts are restored while retroarch.cfg, controller profiles/remaps, saves, states, BIOS, and external installs remain unchanged."
capture_result "Plan 06" "Save round-trip and Repair Wingosy RetroArch profile"

stage "Install N, update N+1, and uninstall preservation"
say "Use a sacrificial Windows profile and two genuine signed beta installers built by the normal release path."
step "Install beta N. Create non-secret test configuration, a populated test database, and permitted ROM-library pointers; record local hashes/counts without recording names or paths."
step "Install beta N+1 over N. Confirm configuration, database contents, ROM pointers, and saves all remain usable."
step "Uninstall Wingosy. Record exactly which app-data directories remain and confirm the documented behavior; do not delete the only backup."
warn "If update or uninstall loses configuration, database contents, ROM pointers, or saves, stop the release and record FAIL."
capture_result "Plan 06" "Clean install, N → N+1 update, and uninstall data behavior"

stage "Candidate controller journey and evidence review"
say "Use the exact candidate build, one wired or Bluetooth XInput controller, and a second standard-mapped controller."
step "Navigate library > details > Play > RetroArch menu > clean exit > Wingosy using the primary controller."
step "Disconnect and reconnect it once. Confirm no stuck direction, duplicate action, or restart requirement."
step "Connect the second standard pad and smoke-test active-pad handoff without duplicate input. Record family and transport, never serial numbers."
step "Review the report and .scratch/transparent-romm-launching/emulator-certification.md. Every promised row needs real Windows runtime evidence before leaving NOT VERIFIED."
step "Confirm git status contains no user data, credentials, copyrighted content, emulator binary, or sensitive evidence."
capture_result "Plan 06" "XInput journey, second pad, six-row ledger, and repository safety review"

stage "Optional draft creation and publication authorization"
if grep -q '\*\*Result:\*\* FAIL' "$REPORT_FILE"; then
  warn "At least one certification check failed. Do not dispatch or publish a beta."
  record_result "Plan 06" "Release authorization" "SKIP" "Publication blocked by failed certification evidence." "$REPORT_FILE"
  pause "Press Enter to finish with publication blocked."
else
  say "This workflow changes external state: it bumps the version, commits and pushes main, builds a signed installer, and creates a draft prerelease."
  say "Before dispatch, confirm main is the exact reviewed source and GitHub Actions has TAURI_SIGNING_PRIVATE_KEY and TAURI_SIGNING_PRIVATE_KEY_PASSWORD. Check presence only; never reveal their values."
  if confirm "Do you explicitly authorize dispatching the Beta workflow from main now?"; then
    open_url "https://github.com/auron-labs/wingosy-launcher/actions/workflows/beta.yml"
    step "Select Run workflow, choose main, and dispatch exactly once."
    step "Wait for the workflow to finish. Record its run URL, candidate commit, beta tag, and draft release URL in the report."
    step "Download the signed installer from the draft and confirm it is byte-for-byte the installer manually accepted. If it differs, leave the release draft and stop."
    step "Open the draft release, verify the candidate commit and certification links, keep This is a pre-release selected, then publish only after every must-pass row is green."
    capture_result "Plan 06" "Exact candidate workflow, draft, and prerelease publication"
  else
    say "Publication remains intentionally deferred. The completed certification report is still usable."
    record_result "Plan 06" "Release authorization" "SKIP" "Publication explicitly deferred by the owner." "$REPORT_FILE"
    pause "Press Enter to finish without changing GitHub."
  fi
fi

finish
say "Certification report: $REPORT_FILE"
