#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

EVIDENCE_DIR="${EVIDENCE_DIR:-.scratch/next-steps/evidence}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)}"
REPORT_FILE="${REPORT_FILE:-$EVIDENCE_DIR/$RUN_ID-manual-acceptance.md}"

mkdir -p "$EVIDENCE_DIR"

record_result() {
  local ticket="$1" check="$2" result="$3" notes="$4" evidence="$5"
  {
    printf '\n## %s — %s\n\n' "$ticket" "$check"
    printf -- '- **Result:** %s\n' "$result"
    printf -- '- **Notes:** %s\n' "${notes:-None recorded}"
    printf -- '- **Evidence:** %s\n' "${evidence:-None recorded}"
  } >> "$REPORT_FILE"
}

capture_result() {
  local ticket="$1" check="$2" result="" notes="" evidence=""
  while [[ ! "$result" =~ ^(PASS|FAIL|SKIP)$ ]]; do
    ask result "Result for $check (PASS, FAIL, or SKIP):"
    result=$(printf '%s' "$result" | tr '[:lower:]' '[:upper:]')
    [[ "$result" =~ ^(PASS|FAIL|SKIP)$ ]] || warn "Enter PASS, FAIL, or SKIP."
  done
  ask notes "Short non-sensitive notes (no ROM names, URLs, tokens, or personal paths):"
  ask evidence "Evidence filename(s), ticket comment, or local-only reference:"
  record_result "$ticket" "$check" "$result" "$notes" "$evidence"
}

banner "Wingosy manual acceptance"

stage "Safety preflight and evidence record"
say "Use Windows 11 and a throwaway Windows account, VM, or sacrificial Wingosy profile."
warn "Do not delete or rename your only Wingosy data. Do not paste credentials, tokens, RomM URLs, ROM names, or personal paths into this wizard."
step "Back up %APPDATA%\\wingosy\\launcher, emulator saves, and permitted test content outside the profile being tested."
step "Keep the backup closed while testing so Wingosy cannot modify it."
if ! confirm "Have you made and checked the backup?"; then
  warn "Stopping before any manual acceptance work. Re-run after the backup exists."
  exit 1
fi
ask WINDOWS_VERSION "Windows 11 version/build (public):"
ask APP_VERSION "Wingosy version under test (Settings > General):"
ask TEST_COMMIT "Exact tested commit SHA:"
ask TESTER "Tester name or non-sensitive handle:"
{
  printf '# Wingosy manual acceptance — %s\n\n' "$RUN_ID"
  printf -- '- **Windows:** %s\n' "$WINDOWS_VERSION"
  printf -- '- **Wingosy:** %s\n' "$APP_VERSION"
  printf -- '- **Commit:** %s\n' "$TEST_COMMIT"
  printf -- '- **Tester:** %s\n' "$TESTER"
  printf -- '- **Safety:** No credentials, tokens, user data, ROM names, or personal paths belong in this report.\n'
} > "$REPORT_FILE"
say "Evidence report: $REPORT_FILE"
pause "Press Enter after the isolated test profile is ready."

stage "Ticket 02 — configured setup survives restart"
say "Use an empty isolated profile, not your everyday Wingosy profile."
step "Launch Wingosy and choose Pair with RomM in the setup wizard. Complete authentication in the browser; enter no credential into this terminal."
step "Back in Wingosy, run Sync Library and wait for an explicit successful completion."
step "Select Finish and verify the desktop library opens."
step "Fully exit Wingosy, start it again, and confirm it remains paired and the synced library loads."
step "Open Settings > BIOS and confirm RomM platform data loads without an unconfigured-server message."
capture_result "Ticket 02" "Pair → Sync → Finish → restart → BIOS"

stage "Ticket 02 — local-only setup"
say "Use a second empty throwaway profile or restore a known-empty VM snapshot."
step "Launch the first-run wizard and choose the local-only/skip-RomM path."
step "Finish setup, fully exit Wingosy, and launch it again."
step "Confirm the library and Settings open normally and the app does not demand an unavailable RomM server."
step "Do not inspect or attach the resulting config file; a successful restart is the acceptance evidence."
capture_result "Ticket 02" "Local-only setup creates a valid default configuration"

stage "Ticket 03 — credential lifecycle"
say "Use an isolated paired profile. Windows Credential Manager, not config.toml, must own usable session tokens."
step "Pair with RomM, sync once, fully exit Wingosy, then start it again."
step "Run Sync Library again to exercise session refresh, then open Settings > BIOS. Both must work without pairing again."
step "Open Windows Credential Manager > Windows Credentials. Confirm a Wingosy/RomM credential exists; never reveal or copy its value."
step "Open %APPDATA%\\wingosy\\launcher\\config\\config.toml in a text editor. Search only for field names access_token, refresh_token, and device_token; no usable value may be present. Do not copy the file into evidence."
step "In Settings > RomM, select Disconnect. Restart Wingosy and confirm it is disconnected; check Credential Manager again and confirm the Wingosy/RomM entry is absent."
note "Do not sabotage Credential Manager permissions. The already-green failure-injection tests cover failed writes without risking the Windows account."
capture_result "Ticket 03" "Pair, refresh, BIOS, sync, token storage, and disconnect"

stage "Ticket 04 — desktop large-catalog pagination"
say "Use the representative large RomM library previously observed with multiple pages. Keep public evidence free of ROM titles."
step "Open the desktop library and confirm only one bounded page renders initially."
step "Use Next page, Previous page, and a distant/last page control. Confirm the page indicator and visible cards change each time."
step "Change search text and platform filters. Confirm pagination resets sensibly and no blank or duplicated page is left behind."
step "Return to the first page and confirm keyboard and mouse focus still work."
capture_result "Ticket 04" "Desktop first render, next/previous/last page, and filter reset"

stage "Ticket 04 — immersive large-catalog pagination"
step "In Settings > General, enable Immersive mode; optionally use F11 for fullscreen."
step "Navigate down through the initial immersive results until the next chunk is requested."
step "Confirm additional games append without replacing the current results, duplicating cards, or losing focus."
step "Continue across at least one more boundary, then use Esc/Back to return to desktop mode."
step "Record behavior and timing only; do not record ROM titles or personal server details."
capture_result "Ticket 04" "Immersive incremental loading and stable focus"

stage "Ticket 07 — support and redaction path"
step "Open Settings > General > Open Logs Folder. Confirm it opens %APPDATA%\\wingosy\\launcher\\data\\logs\\, matching README.md."
step "Select Report a Problem. Confirm the browser opens the canonical Auron Labs bug-report route, but do not submit a test issue."
step "Draft a local-only sample containing app version, Windows version, reproduction steps, expected/actual behavior, and one relevant redacted log excerpt."
step "Confirm the draft contains no config.toml, database, credentials/tokens, RomM URL, ROM names/paths, or personal path segments. Delete the local draft when satisfied."
step "Open BETA_RELEASE_NOTES.md and confirm it names Auron Labs maintainers as owner, best-effort review with no guaranteed response time, and the P0 cohort expansion gate."
capture_result "Ticket 07" "Logs folder, report route, safe report, owner, response expectation, and cohort gate"

stage "Ticket 09 — primary XInput, deadzone, and hot-plug"
say "Use one real wired or Bluetooth XInput/standard-mapped controller. Record family and transport, not a serial number."
step "With keyboard first, confirm arrows navigate, Enter confirms, and Esc goes back."
step "In Settings > General, change Controller deadzone within 0.10–0.80, restart Wingosy, and confirm it persists. Select Reset deadzone and confirm 0.35."
step "Enter Immersive mode. Use D-pad/stick to navigate, South/Confirm to open details, East/Back to return, and the menu action where offered. Each press must emit once."
step "While idle, disconnect the controller. Confirm no direction remains held and keyboard navigation still works."
step "Reconnect it and confirm navigation resumes without restarting Wingosy or duplicating an action."
capture_result "Ticket 09" "Primary XInput navigation, bounded deadzone, keyboard fallback, and reconnect"

stage "Ticket 09 — second controller and unsupported-pad boundary"
step "Connect a second standard-mapped controller while the first remains connected."
step "Press one direction on the active pad. Confirm only one launcher movement occurs."
step "Disconnect the active pad, then use the other. Confirm it becomes active without stuck or duplicate input."
step "If an unsupported/non-standard pad is available, connect it and confirm it produces no launcher action while keyboard recovery remains available. Otherwise record SKIP for that optional observation."
step "For gameplay-binding problems, verify the documented recovery path is RetroArch > Input > RetroPad Binds > Port 1 > Set All Controls > Save Controller Profile."
capture_result "Ticket 09" "Second standard pad, active-pad handoff, and unsupported-pad boundary"

stage "Review evidence and close eligible tickets"
say "Review $REPORT_FILE. A FAIL keeps its ticket ready-for-human; a justified SKIP must not be treated as passing a required check."
if grep -q '\*\*Result:\*\* FAIL' "$REPORT_FILE"; then
  warn "At least one check failed. Do not resolve its ticket; attach the non-sensitive evidence and open a focused follow-up."
else
  say "No FAIL result was recorded. Check every required row before resolving anything."
fi
step "For each passing ticket, append a dated comment summarizing the tested Windows/app/commit versions and linking this local evidence report."
step "Check only criteria directly proven by this run, add an Answer section, then change Status: ready-for-human to Status: resolved."
step "Update .scratch/next-steps/spec.md only after its dependent tickets are actually resolved."
warn "Do not commit screenshots or evidence containing user data, credentials, ROM names, server URLs, or personal paths."
pause "Press Enter after reviewing the report and ticket rules."

finish
say "Evidence report: $REPORT_FILE"
