#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPOSITORY_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd -P)"
EVIDENCE_DIR="$REPOSITORY_ROOT/.scratch/next-steps/evidence"
RUN_ID="$(date +%Y%m%d-%H%M%S)"
REPORT_FILE="$EVIDENCE_DIR/${RUN_ID}-controller-acceptance.md"
REPORT_RELATIVE_PATH=".scratch/next-steps/evidence/${RUN_ID}-controller-acceptance.md"

if [[ -e "$REPORT_FILE" ]]; then
  REPORT_SUFFIX=2
  while [[ -e "$EVIDENCE_DIR/${RUN_ID}-${REPORT_SUFFIX}-controller-acceptance.md" ]]; do
    REPORT_SUFFIX=$((REPORT_SUFFIX + 1))
  done
  RUN_ID="${RUN_ID}-${REPORT_SUFFIX}"
  REPORT_FILE="$EVIDENCE_DIR/${RUN_ID}-controller-acceptance.md"
  REPORT_RELATIVE_PATH=".scratch/next-steps/evidence/${RUN_ID}-controller-acceptance.md"
fi

mkdir -p "$EVIDENCE_DIR"

PASS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0
REPLY=""

on_interrupt() {
  printf '\n\nReport preserved at %s\n' "$REPORT_RELATIVE_PATH"
  exit 130
}
trap on_interrupt INT

read_line() {
  if ! IFS= read -r REPLY; then
    printf '\n'
    warn "Input ended before the wizard finished. Report preserved at $REPORT_RELATIVE_PATH"
    exit 1
  fi
  REPLY="${REPLY%$'\r'}"
}

record_result() {
  local label="$1" result="$2"
  case "$result" in
    PASS) PASS_COUNT=$((PASS_COUNT + 1)) ;;
    FAIL) FAIL_COUNT=$((FAIL_COUNT + 1)) ;;
    SKIP) SKIP_COUNT=$((SKIP_COUNT + 1)) ;;
  esac
  printf -- '- **%s:** %s\n' "$label" "$result" >> "$REPORT_FILE"
}

capture_result() {
  local label="$1" result
  while :; do
    printf '  Result for %s (y=PASS, n=FAIL, s=SKIP): ' "$label"
    read_line
    case "${REPLY,,}" in
      y) result=PASS ;;
      n) result=FAIL ;;
      s) result=SKIP ;;
      *) warn 'Enter only y, n, or s.'; continue ;;
    esac
    record_result "$label" "$result"
    return 0
  done
}

{
  printf -- '- **Run ID:** %s\n' "$RUN_ID"
  printf '\n'
} > "$REPORT_FILE"

stage 'Ready'
say 'Use the current Wingosy build. Put the one 8BitDo controller in XInput/Windows mode, disconnect other controllers, enter Immersive, then press Enter.'
pause 'Press Enter when ready.'

stage 'Launcher/details'
say 'Press one D-pad direction once and verify it moves once. Press South once and verify details opens once.'
step 'Use D-pad/stick directions to visibly select enabled details actions. Select Favorite, press South once, and verify it toggles once without Play.'
step 'Press East once and verify the library returns. Press Menu once and verify Settings opens.'
capture_result 'Launcher/details'

stage 'Drift/reconnect'
say 'With the stick centered, wait 10 seconds; it must stay still. Fully deflect it and verify movement works.'
step 'Hold a direction until it repeats, disconnect the controller, and verify movement stops. Reconnect without restarting Wingosy, then press one direction once and verify exactly one move.'
note 'Do not change or restart the deadzone setting; its bounds, persistence, and reset are already automated.'
capture_result 'Drift/reconnect'

stage 'RetroArch + closeout'
say 'Using permitted content, select Play once. Verify gameplay responds, the configured RetroArch menu opens, and a clean exit returns to Wingosy.'
step 'After returning, send one launcher input and verify it works once. If permitted content is unavailable, enter s; the ticket remains ready-for-human.'
capture_result 'RetroArch'

if (( FAIL_COUNT > 0 )); then
  OVERALL_RESULT='FAIL/ready-for-human'
elif (( SKIP_COUNT > 0 )); then
  OVERALL_RESULT='SKIP/ready-for-human'
else
  OVERALL_RESULT='PASS'
fi
printf -- '- **Overall:** %s\n' "$OVERALL_RESULT" >> "$REPORT_FILE"
printf -- '- **Scope:** One 8BitDo controller only; second-controller and unsupported-pad checks were not part of this run.\n' >> "$REPORT_FILE"

_clear
printf '\n%s%s  ✓ Controller acceptance complete%s\n' "$BOLD" "$GREEN" "$RESET"
printf '  Report: %s\n' "$REPORT_RELATIVE_PATH"
printf '  Overall: %s\n' "$OVERALL_RESULT"
if [[ "$OVERALL_RESULT" != 'PASS' ]]; then
  printf '  %sTicket 09 remains ready-for-human.%s\n' "$RED" "$RESET"
fi
